global:
  params:
    p1: 1001
    p2: 20033

spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:2000/applications

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"