server:
  port: 8888  # Port for the Config Server

spring:
  application:
    name: config-server  # Name of the application
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/config-repo  # URL of the Git repository containing configuration files
          default-label: main       # Branch of the Git repository (e.g., main, master)
          clone-on-start: true      # Clones the repository when the server starts
          search-paths: '{application}'  # Organize configurations in folders based on the application name
      enabled: true  # Enable the Config Server

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.config.server: DEBUG  # Set to DEBUG to help with troubleshooting if needed

# Security (Optional): If you want to secure access to the Config Server
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
