customers-service-dev:
  params:
    x: 31
    y: 31

spring:
  application:
    name: customers-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: lamaachi
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  feign:
    client:
      config:
        default:
          # Optional: Customize Feign client settings
          connectTimeout: 5000
          readTimeout: 5000
  customers-service:
    url: http://localhost:8081  # or your actual service URL

server:
  port: 8081
