customers-service-dev:
  params:
    x: 31
    y: 31

spring:
  application:
    name: customers-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/customer}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:lamaachi}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:2000}
server:
  port: 8085
